# Generated by Django 4.2.2 on 2023-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=5, max_length=120),
            preserve_default=False,
        ),
    ]
