# Generated by Django 4.2.2 on 2023-06-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespersons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='name',
        ),
    ]
