# Generated by Django 4.2.2 on 2023-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_create',
            field=models.DateField(blank=True),
        ),
    ]
