# Generated by Django 4.2.2 on 2023-07-06 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date_create',
        ),
        migrations.AddField(
            model_name='sale',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
